### ISSUE TITLE
Using port other than 8081 

### ISSUE THREAD

**Issue by Jatin-WIAI** [hellohaptik/chatbot_ner#439] opened 2021-09-21 13:37 UTC
Hi, I am trying to use chatbot_ner for my project. port 8081 is currently occupied in my server and I cannot stop that process. I installed chatbot_ner container to map to a different port (2001), it  got installed properly, but when I am not getting any response while I am using the API. 
Can you please explain what could be going wrong. Also, what is the correct method to use a port other than 8081. 
Thanks!

**Comment by chiragjn** [comment] 2021-09-21 21:30
Hello, changing the port in `docker-compose.yml` should bind it to a different port
https://github.com/hellohaptik/chatbot_ner/blob/72a48c8801f2708eff686388040667b74459efec/docker/docker-compose.yml#L30-L32

Can you please post how you are running the container and how you are testing it?

**Comment by chiragjn** [comment] 2021-09-27 14:41
I am closing this issue, if the problem is not resolved, please feel free to re-open and tag me.

**Closed by chiragjn** 2021-09-27 14:41 UTC
