### ISSUE TITLE
Issues on Adding new data from csv file to datastore 

### ISSUE THREAD

**Issue by prasannaonchip** [hellohaptik/chatbot_ner#268] opened 2019-06-18 10:09 UTC
document named  chatbot_ner/docs/adding_entities.md in that 
Adding new data from csv file to datastore
Make sure to start the engine you configured with datastore( eg. elasticsearch)
$ ~/chatbot_ner_elasticsearch/elasticsearch-5.5.0/bin/elasticsearch -d
how can we the  start the engine configured with datastore
how we can configure datastore

thanks in advance.

**Comment by chiragjn** [comment] 2019-06-26 10:37
Hello, sorry for the late reply, if you have set up using Docker as mentioned in https://github.com/hellohaptik/chatbot_ner/blob/develop/docs/install.md you would already have elasticsearch running, after you run `docker-compose up --build -d` in Step 2

You can verify by running
```
cd chatbot_ner/docker/
docker-compose ps
```

To index data in elastic search, you can execute the following 

```
docker exec -it <> bash
```

Once inside the container start a python shell

```
python manage.py shell
```

Then in the python shell, run the following. In the `db.populate` call below pass the path to csv files you want to index. The name of the file should be the name of the entity and the extension should be `.csv`. For sample files look here https://github.com/hellohaptik/chatbot_ner/blob/develop/data/entity_data

```
from datastore import DataStore
csv_file = 'data/entity_data/city.csv' # example file path to the csv file
db = DataStore()
db.populate(csv_file_paths=[csv_file,])
```

I am keeping this ticket open because we need to update our documentation for docker.

**Comment by prasannaonchip** [comment] 2019-06-26 13:02
after following the this producer 
after the executing the these steps
db = DataStore()
i am getting the error is 
EngineConnectionException: 'Chatbot NER datastore was unable to connect to elasticsearch. Please make sure the elasticsearch service is reachable.'
please reply 
thanks in advance.

**Comment by prasannaonchip** [comment] 2019-06-27 06:23
For Adding new data from csv file to datastore
$ ~/chatbot_ner_elasticsearch/elasticsearch-5.5.0/bin/elasticsearch -d
where i can get the source for this to run the elasticsearch.
here you people are mentioned in the documentation how to configure the in config.example.

But why gain you people mentioned in  chatbot_ner/docs/adding_entities.md
as Make sure to start the engine you configured with datastore( eg. elasticsearch)

$ ~/chatbot_ner_elasticsearch/elasticsearch-5.5.0/bin/elasticsearch -d

**Comment by prasannaonchip** [comment] 2019-06-27 10:20
please give reply

**Comment by chiragjn** [comment] 2019-06-27 11:55
Hello, I have updated the docs here for adding new entities: https://github.com/hellohaptik/chatbot_ner/blob/07657b6c664753a05bd9f5f7dbc4792d7d6aa654/docs/adding_entities.md

That PR is under review and will be merged soon.

**Comment by prasannaonchip** [comment] 2019-06-28 05:15
Hi 
i worked on the updated document which you are given above, i followed the same steps for adding new enties by using this document 
https://github.com/hellohaptik/chatbot_ner/blob/develop/docs/adding_entities.md
after that also i am getting the error like this 

EngineConnectionException: 'Chatbot NER datastore was unable to connect to elasticsearch. Please make sure the elasticsearch service is reachable.'
please reply fast
thanks in advance

**Comment by prasannaonchip** [comment] 2019-06-28 10:12
without using the docker how can i use these steps has you mentioned for adding entities.
if it  possible please tell the procedure of adding_entities.
thanks i advance

**Comment by prasannaonchip** [comment] 2019-06-28 12:50
please reply as soon as possible

**Comment by prasannaonchip** [comment] 2019-07-01 05:59
can you please post the procedure of hellohaptik chatbot_ner implementation without using the docker.

**Comment by chiragjn** [comment] 2019-07-01 06:49
You can find the installation steps without docker from the past here:
Installation:
https://github.com/hellohaptik/chatbot_ner/blob/e69c2a6980398753836485efe86bd2b4e2c132c1/docs/install.md

Adding entities:
https://github.com/hellohaptik/chatbot_ner/blob/e69c2a6980398753836485efe86bd2b4e2c132c1/docs/adding_entities.md

However, please note that we do not recommend setup without docker as it is hard to guarantee reproducibility. We would still recommend setting up with docker as mentioned in the docs on develop

**Closed by chiragjn** 2019-07-01 06:49 UTC
Labels: documentation

**Comment by prasannaonchip** [comment] 2019-07-02 06:59
helloaptik chatbot_ner is working for python version 2.x with and without docker.
we have one doubt is it(hellohaptik chatbotbot_ner) supports for python version 3.x
